apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-staff-timetable-config
  namespace: "${NAMESPACE}"
data:
  DB_BACKEND: "postgres"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  ENVIRONMENT: "production"
