apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: "${NAMESPACE}"
  labels:
    app: n8n
data:
  # PostgreSQL Configuration
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "postgres"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "${N8N_DB_NAME}"

  # n8n Host Configuration
  N8N_HOST: "${N8N_HOST}"
  WEBHOOK_URL: "https://${N8N_HOST}/"
  N8N_PROTOCOL: "https"
  N8N_PORT: "5678"

  # n8n Features
  N8N_METRICS: "true"
  N8N_BASIC_AUTH_ACTIVE: "false"
  N8N_PERSONALIZATION_ENABLED: "false"
  N8N_DIAGNOSTICS_ENABLED: "false"
  N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
  N8N_TEMPLATES_ENABLED: "true"
  N8N_ONBOARDING_FLOW_DISABLED: "false"

  # Redis/Queue Configuration
  QUEUE_BULL_REDIS_HOST: "redis"
  QUEUE_BULL_REDIS_PORT: "6379"
  QUEUE_BULL_REDIS_DB: "1"

  # Timezone
  GENERIC_TIMEZONE: "America/Mexico_City"
  TZ: "America/Mexico_City"

  # Performance
  N8N_PAYLOAD_SIZE_MAX: "16"
  EXECUTIONS_DATA_PRUNE: "true"
  EXECUTIONS_DATA_MAX_AGE: "168"
