apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-storage
  namespace: "${NAMESPACE}"
  labels:
    app: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
